---
title: "simulation results"
author: "Scott Sun"
date: "2022-12-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r, echo=FALSE}
summarizing_table <- function(lm_simu_rlt, p = 1, num_methods = 3, only_beta = FALSE) {
  if (only_beta) {
    tbl_names <- c(
        "",
        paste0("$\\", paste("beta", seq(0,p), sep = "_"), "$")
      )
  } else {
    tbl_names <- c(
        "",
        paste0("$\\", paste("mu", seq_len(p), sep = "_"), "$"),
        paste0("$\\", paste("sigma^2", seq_len(p), sep = "_"), "$"),
        "$\\sigma^2$",
        paste0("$\\", paste("beta", seq(0,p), sep = "_"), "$")
      )
  }
  est_m <- lm_simu_rlt$estimates %>%
    group_by(estimator_type) %>%
    summarise_all(.funs = mean,) %>%
    mutate_if(is.numeric, ~ as.character(round(., digits = 3)))
  est_v <- lm_simu_rlt$estimates %>%
    group_by(estimator_type) %>%
    summarise_all(.funs = var) %>%
    mutate_if(is.numeric, ~ as.character(round(., digits = 3)))
  est_coverage <- lm_simu_rlt$coverage %>%
    group_by(estimator_type) %>%
    summarise_all(.funs = mean) %>%
    mutate_if(is.numeric, ~ as.character(round(., digits = 3)))
  rbind(est_m, est_v, est_coverage) %>%
    knitr::kable(
      booktabs = TRUE,
      col.names = tbl_names,
      escape = FALSE
    ) %>%
    kableExtra::group_rows("Mean", 1, num_methods) %>%
    kableExtra::group_rows("Variance", 1 + num_methods, 2 * num_methods) %>%
    kableExtra::group_rows("Coverage rate", 2 * num_methods + 1, 3 * num_methods) %>%
    kableExtra::kable_styling(latex_options = "HOLD_position", font_size = 7)
}
```

# E-M Simple Linear Regression

```{r, echo=FALSE}
high_missingness <- readRDS("./simulation_rlt/simple_linear/p50sigmaSq25.rds")
mid_missingness <- readRDS("./simulation_rlt/simple_linear/p80sigmaSq25.rds")
low_missingness <- readRDS("./simulation_rlt/simple_linear/p95sigmaSq25.rds")
high_missingness_high_noise <- readRDS("./simulation_rlt/simple_linear/p50sigmaSq100.rds")
```

## Missingness rate
### Low
```{r, echo=FALSE}
summarizing_table(low_missingness)
```

### Medium
```{r, echo=FALSE}
summarizing_table(mid_missingness)
```

### High
```{r, echo=FALSE}
summarizing_table(high_missingness)
```
## High Noise-signal ratio
```{r, echo=FALSE}
summarizing_table(high_missingness_high_noise)
```

## Misspecified X (using a Normal distribution to model a right skewed Exponential distributed data)

```{r, echo=FALSE}
high_missingness_misspec <- readRDS("./simulation_rlt/simple_linear/misspecp50sigmaSq25.rds") %>% 
  lapply(function(x) x[,-(1:3)])
low_missingness_misspec <- readRDS("./simulation_rlt/simple_linear/misspecp95sigmaSq25.rds") %>% 
  lapply(function(x) x[,-(1:3)])
```

```{r, echo=FALSE}
summarizing_table(high_missingness_misspec, only_beta = TRUE)
```

```{r, echo=FALSE}
summarizing_table(low_missingness_misspec, only_beta = TRUE)
```

# E-M Multivariate Linear Regression

```{r}
multvariate_mcar <- readRDS("./simulation_rlt/mult_linear/gamma2p80sigmaSq25.rds")
multvariate_mar <- readRDS("./simulation_rlt/mult_linear/gamma-12p80sigmaSq25.rds")
```

## MCAR

```{r, echo=FALSE}
summarizing_table(multvariate_mcar, p = 3, num_methods = 2)
```

## MAR

```{r, echo=FALSE}
summarizing_table(multvariate_mar, p = 3, num_methods = 2)
```
