---
title: "vignette: multivariate example"
author: "Scott Sun"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(progress)
source("./multi_linear.R")
```

```{r}
x1 <- rnorm(200, mean = 10, sd = 5)
x2 <- rnorm(200, mean = 0, sd = 1)
x3 <- rnorm(200, mean = 10, sd = 5)
y <- rnorm(200, mean = 10 + 1 * x1 + 3 * x2 + 0 * x3, sd = 5)
p1 <- 1 / (1 + exp(-(2 + 1 * x2)))
p3 <- 0.8
m1 <- rbinom(200, 1, p1)
m3 <- rbinom(200, 1, p3)
x1 <- ifelse(m1 == 1, x1, NA)
x3 <- ifelse(m3 == 1, x3, NA)
X <- cbind(1, x1, x2, x3)

cat("missingness rate", mean(m1), mean(m3), "\n")
model <- y ~ x1 + x2 + x3
print(
  c(sum((residuals(lm(model))) ^ 2) / (length(y) - 2), 
    coef(lm(model)))
  )
```

```{r}
params <- list(
  mu = c(10, 10, 10),
  Sigma_x = diag(c(50, 50, 50)),
  sigma_sq = 1,
  b = c(5, 0, 0, 0)
)
params <- em(params, y, X)
params
```

```{r}
em_bootstrapping(5000, params, y, X) %>% boot_confint()
```

```{r}
em_vcov(params, y, X) %>% 
  diag() %>% 
  sqrt()
```


```{r}
em_theoretical_ci(params, y, X)
```


